### ISSUE TITLE
Periodically changing 'LastExportTime' item data results in items not matching

### ISSUE THREAD

**Issue by blablubbabc** [knokko/custom-items-gradle#138]
A user of one of my plugins (Shopkeepers) reported an issue with items created by this plugin not being accepted in Shopkeeper trades after a while. The issue seems to be caused by this plugin periodically changing the custom items in player inventories to store a new different timestamp in their `LastExportTime` tag (this might involve a plugin reload, not sure). This difference in item data causes items to no longer match, resulting in the items no longer being accepted in Shopkeeper trades.

Would it be possible to avoid using this mechanism of storing periodically changing data inside of items?

Note that this issue is not limited to the context of Shopkeeper trades: Mismatching items can cause issues in any context in which Minecraft or some other plugin compares items by their NBT data. For instance, in vanilla Minecraft, for stackable types of items, players may encounter item stacking issues when they try to stack an item that had its internal timestamp changed with some items that did not have their timestamp updated (for example because they are stored inside a chest or other type of container, which is one of potentially many cases which the item updater of this plugin does not acocunt for). Another not covered case are custom (non-Shopkeeper) villager trades. And also the item on the cursor of an open inventory is currently ignored.
There are probably countless more cases in which Minecraft stores items which this plugin does not account for currently. I also doubt that a plugin will ever be able to cover all of these possible cases, nor that this periodic scanning could be implemented efficiently.
And even if this plugin would account for all vanilla cases, I doubt that it will be able to account for all cases in which some other plugin might store or reference an item stack and then under some circumstances compare it with item stacks of players that went through this periodic updating.

Hence the suggestion to somehow find a way for this plugin to work without this periodic changing item data (or ideally even without this periodic scanning and replacing of items in player inventories).

I haven't checked in detail why this item updating is even required, or what is stored in this `BooleanRepresentation`. But maybe it would be enough to store only the CustomItem name and then dynamically lookup any data for the CustomItem with this name, instead of encoding this data inside the items themselves.

**Comment by knokko** [comment]
Thank you for all the inspiration! I especially like the idea of letting the server admin choose whether he wants automatic item updating and I agree that it would be better if `ItemStack`s are only updated when the corresponding custom item actually changed.

But, I don't see why it matters whether I compare item version numbers or the timestamp when the item was last modified, since they come down to the same thing (both are numbers that only change when the item is modified).

Keeping track of the history of all custom items solves the `BooleanRepresentation` problem (like you said, storing it per `ItemStack` is not optimal), but it causes another problem: the history will grow each time the admin changes items, but it will *never* shrink (unless the admin does it manually). If many change are made, the history will also remember all the old custom item versions, *even if no single `ItemStack` still uses it*. Storing it per `ItemStack` avoids this problem since the data will be deleted whenever the `ItemStack` is destroyed. This results in more predictable memory usage: exactly 1 version of each custom item is stored per custom `ItemStack`. (I guess the history will still use less memory in most cases, but it is much harder to predict.)

Also, I don't believe bytecode modifications are better than periodic updating checks. Profiling data from running servers shows that this takes ~0.01% of the server tick time. And even if it does get out of hand, I could make the updating period longer. And how would iterating over all entities every 5 seconds be expensive? The server has to do this 20 times per second anyway to update them (and these updates are more expensive than just checking their equipment). Inventory updating only happens when the item updater actually *changes* an item, which is quite rare.

Finally, I respect your choice of not adding special integration (it's not nice indeed and could cause client-sync problems in your case).
