### ISSUE TITLE
Considering an update to support custom snowballs and other projectiles?

### ISSUE THREAD

**Issue by HansOffice** [knokko/custom-items-gradle#201]
Maybe it's a good choice to take to make grenades or other interesting gadgets

**Comment by knokko** [comment]
This plug-in doesn't allow any 'real' projectiles because they suffer from several problems:
- Their velocity is hard to control
- They tend to change direction when they have in-flight explosion effects
- Their gravity can't be controlled properly

Why do you need to use snowballs anyway? You can configure the speed and gravity of custom projectiles, which allows you to give them the same flight directory as a snowball.

**Comment by knokko** [comment]
I will close this for now due to inactivity. Anyone is free to reopen it when they explain why this feature would be needed.
